import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { PGlite } from '@electric-sql/pglite';
import { drizzle } from 'drizzle-orm/pglite';
import type { NodePgDatabase } from 'drizzle-orm/node-postgres';
import { createRepository } from '../src/db/repository';
import * as schema from '../src/db/schema';
import data from '../seed/garden.json';
import type { Seed } from '../src/lib/types';
import { today } from '../src/lib/dates';
import { buildContext, historyDecisions, makePlan } from '../src/lib/planner';
const seed = data as Seed;
test('PostgreSQL migration, repeated import, batch record/undo, CRUD and generation lock', async () => {
  const pg = new PGlite();
  try {
    const journal = JSON.parse(readFileSync('drizzle/meta/_journal.json', 'utf8'));
    for (const entry of journal.entries) await pg.exec(readFileSync(`drizzle/${entry.tag}.sql`, 'utf8'));
    const repo = createRepository(drizzle(pg, { schema }) as unknown as NodePgDatabase<typeof schema>);
    await repo.seed(seed); await repo.seed(seed);
    let state = await repo.state();
    assert.equal(state.plants.length, 39); assert.equal(state.events.length, 495); assert.equal(state.groups.length, 6);
    const soil = state.plants.filter(p => ['P022', 'P023'].includes(p.code));
    const requestId = crypto.randomUUID();
    const input = { requestId, occurredOn: today(), action: 'watered' as const, plantIds: soil.map(p => p.id), moisture: 'unknown' as const, notes: 'Kiểm tra buổi tưới' };
    const recorded = await repo.record(input); await repo.record(input);
    await assert.rejects(repo.record({ ...input, plantIds: [soil[0].id] }), /nội dung khác/);
    state = await repo.state(); assert.equal(state.sessions.length, 1); assert.equal(state.events.length, 497);
    assert.equal(state.sessions[0].plantIds.length, 2);
    const hydro = state.plants.find(p => p.code === 'P004')!;
    await assert.rejects(repo.record({ ...input, requestId: crypto.randomUUID(), plantIds: [soil[0].id, hydro.id] }), /thủy sinh/);
    assert.equal((await repo.state()).events.length, 497, 'Failed batch is atomic');
    await repo.undo(recorded.id); await repo.undo(recorded.id);
    state = await repo.state(); assert.equal(state.events.filter(e => !e.voidedAt).length, 495);
    assert((await repo.record(input)).undone, 'Replay of an undone request cannot recreate the session');
    const groupId = crypto.randomUUID();
    await repo.saveGroup({ name: 'Rau cạnh cửa', plantIds: soil.map(p => p.id) });
    const group = (await repo.state()).groups.find(g => g.name === 'Rau cạnh cửa')!;
    await repo.saveGroup({ id: group.id, name: 'Rau cạnh cửa', plantIds: [soil[0].id] });
    assert.equal((await repo.state()).groups.find(g => g.id === group.id)!.plantIds.length, 1);
    await repo.deleteGroup(group.id); assert(!(await repo.state()).groups.some(g => g.id === group.id));
    await repo.archivePlant(soil[0].id);
    await assert.rejects(repo.record({ ...input, requestId: crypto.randomUUID() }), /lưu trữ/);
    await repo.archivePlant(soil[0].id, true);
    const context = buildContext(state.garden, soil, state.events, today(), 'history');
    const first = await repo.startPlan(groupId, 'history', context);
    await assert.rejects(repo.startPlan(crypto.randomUUID(), 'history', context), /đang được tạo/);
    const result = makePlan(context, historyDecisions(context), 'history', null, first.id);
    await repo.finishPlan(first.id, result, context);
    assert.equal((await repo.startPlan(groupId, 'history', context)).existing?.id, result.id);
    assert.equal((await repo.state()).plans.length, 1);
    await repo.seed(seed); assert.equal((await repo.state()).events.length, 497);
    const tables = await pg.query<{ table_name: string }>("SELECT table_name FROM information_schema.tables WHERE table_schema='public'");
    assert(!tables.rows.some(t => t.table_name === 'import_batches'));
  } finally { await pg.close(); }
});
